language: java
jdk:
    - oraclejdk8
    deploy:
    provider: heroku
    api_key:
        secure: R3cqMwBXp21ixCuzXauve3FQPC4r7VBuDXfVO6ViUIG5pUef6vFrdcLqDJB5d93u0Y0qQkAUmvI1tf27dP9Z2iZJRGmv9lolmCDZcwCTeUC564ymkySatRUlGAOQR/h1Us4+lFSPZSlCf1gerneNB6q8rg4mH6HWMfs97LsmQbUgZMAu0EifbEpeARzIIrImq7+awfmdppv0slEV0OktJX0p/zMGSwQ4pJkh9Zou01NLca5qoUFreKP0WfeAiDy4nZsNKD0c7Ye0NQywOvBgP5MZpO9HD3WpHBYCGJu0E+VXFHtlvLX6yddc5lAA1Dvi5x/8OFmompG1joPtrUkrkFhaAnTAUetOjnIUdNiiY+jxJ4HHAl3SkialM9y1DMCFFftx0b2WKiy6gUxTSnSi08Oj7LN2XOp8nSgUBwlBAxjTxRyyVbGaFZBSmvg4G8uQIR7TN5RYJQwjJC3GwYvTYgfg0qw54Eb/SyMQzW2dXmoYw9bp+1ylfJAikC9fhbNHC8z+O54WNa6S0xZzui6LZt5Kwf5hN8sJma1VYOMlDLR6g6P2fzhVdENBeH6jpdUW0Ub1xq812PpR7alYiynYCxn8sCAbJ0Z2sHWph79Mke9eEK9nUAfb6+mKNq3UYkXralKjzJmgD6wmorH0r4+Hzv7wN2MqTM5cp+tcc8enLrE=
