language: java
jdk:
  - oraclejdk8
deploy:
provider: heroku
api_key:
  secure: fEmAzUm9cP9nT51opOrT+TLXONP3xZiFT1djp/z/461e8Zl7eRtYZWBPEXzx422hKmMivcIpU4TpEQXd61WIVRpGi09eO9qc46q5MtTZSHXPQFVMFMicOiblffKKmj03yicTjFOuntyNtKLSdU+wBGP3SS2FiX9LWbTNo0arswRpAFFqxjIUIzY2F9fAOsBeIil9jOFdSpZMVNPpASllu+1lF4m/GQpZq1VwcjpxJ9NxFImDZ4ZGPP7yUeuZ7U/8ccXmb/kqy6v24QPb0FZTLTzWCJZBm60G35mzzRR8X3qvB11qBld1oOYhjWRQPlLV3W22HjaLqRinPpEhjTFH3dh0EhVlBIHYWdqtiArUJUvd5rbKTjV4mgMeY67GIdICSnNeEpFyrWwE1YbXmYi5Fo7kLqgRYXn/vlhzJfPlxmBL4BSKtRPfTA4NFOvdzSIwZXd/6TAsQf1msC54wARkg6USLHXedVqXz1hf4AvHCTf23SlJizbZ90X0zmbJJJeddl1Ugc/A+GcXlMlMeHGiOCf+IB1OUKIWhQ22TDb6HnW7R6fCGSY7dOu6r1gBgrn8xY152EzgR30/lgLUYpMvUNFaDSBQdCqjFCJjSwad6VLTl3T4bkpwYCV9VS6J9s6UNKBUfM0lvMgk4FT5tEtbOCdb+Xmrsic7LNs8oyqgvJA=
